# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: checkout repository
      
     
    - name: Connect to EC2 instance
       run:|
          ssh -o StrictHostKeyChecking=no -i ${{ EC2_DEPLOYMENT_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} "cd /project2/MM-project1-backend/ && git pull"
  
    - name: Install Ruby dependencies
       run:|
          cd /project2/MM-project1-backend/
          bundle install --deployment --without development test
        
    - name: Build Docker Image
      run: |
        cd /project2/MM-project1-backend/
        sudo docker build ./
  
  
  
 # test:
   # runs-on: ubuntu-latest
   # services:
     # postgres:
       # image: postgres:11-alpine
       # ports:
        #  - "5432:5432"
       # env:
      #    POSTGRES_DB: postgres
     #     POSTGRES_USER: rubypostgres
    #      POSTGRES_PASSWORD: rubysecret123
   # env:
    #  RAILS_ENV: test
    #  DATABASE_URL: "mm-project2-database.c1g4u7ocjofl.us-east-1.rds.amazonaws.com"
    #steps:
     # - name: Checkout code
      #  uses: actions/checkout@v3
      # Add or replace dependency steps here
     # - name: Install Ruby and gems
       # uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
       # with:
       #   bundler-cache: true
      # Add or replace database setup steps here
      #- name: Set up database schema
       # run: bin/rails db:schema:load
      # Add or replace test runners here
      #- name: Run tests
       # run: bin/rake

 
